### ISSUE TITLE
Too many messages "Telemetry Logging Turned off." at console

### ISSUE THREAD

**Issue by boitcex** [microsoft/jmeter-performance-analyzer-devops-extension#12]
![image](https://user-images.githubusercontent.com/2488949/189888155-e87f8bae-0880-4e86-a66f-1259321c2600.png)
**Actual result**: Too many messages "Telemetry Logging Turned off." on the console in case the feature "Telemetry Data Collection" is disabled in the pipeline configuration
**Expected**: 1 notification will be enough

**Comment by 5-k** [comment]
This has been fixed in 1.5.49. With the latest update in case user turned off telemetry, it will not console log all details.
In case user enables to turn it on, turn on message will be published once.

FYI We recommend turning the telemetry on. We try to identify any failures and the logs helps mitigate any issues. We do not and cannot access any personal data and logs are strictly used for debug purposes.
